// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StudyPlatform.Models;

public partial class StudyPlatformContext : DbContext
{
    public StudyPlatformContext(DbContextOptions<StudyPlatformContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccomplishAchievement> AccomplishAchievements { get; set; }

    public virtual DbSet<Achievement> Achievements { get; set; }

    public virtual DbSet<BoughtSubject> BoughtSubjects { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Following> Followings { get; set; }

    public virtual DbSet<Progress> Progresses { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    public virtual DbSet<TopicProgress> TopicProgresses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccomplishAchievement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Accompli__3214EC073D103B13");

            entity.ToTable("AccomplishAchievement");

            entity.HasOne(d => d.Achievement).WithMany(p => p.AccomplishAchievements)
                .HasForeignKey(d => d.AchievementId)
                .HasConstraintName("FK__Accomplis__Achie__5441852A");

            entity.HasOne(d => d.User).WithMany(p => p.AccomplishAchievements)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Accomplis__UserI__5535A963");
        });

        modelBuilder.Entity<Achievement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Achievem__3214EC07558ABA9F");

            entity.ToTable("Achievement");

            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        modelBuilder.Entity<BoughtSubject>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BoughtSu__3214EC073576AFF1");

            entity.ToTable("BoughtSubject");

            entity.Property(e => e.Feedback).HasMaxLength(255);

            entity.HasOne(d => d.Subject).WithMany(p => p.BoughtSubjects)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__BoughtSub__Subje__47DBAE45");

            entity.HasOne(d => d.User).WithMany(p => p.BoughtSubjects)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__BoughtSub__UserI__48CFD27E");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Chapter__3214EC07CAB9C806");

            entity.ToTable("Chapter");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.HasOne(d => d.Subject).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__Chapter__Subject__398D8EEE");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comment__3214EC071251393B");

            entity.ToTable("Comment");

            entity.Property(e => e.Content).HasMaxLength(255);

            entity.HasOne(d => d.Question).WithMany(p => p.Comments)
                .HasForeignKey(d => d.QuestionId)
                .HasConstraintName("FK__Comment__Questio__440B1D61");

            entity.HasOne(d => d.User).WithMany(p => p.Comments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Comment__UserId__44FF419A");
        });

        modelBuilder.Entity<Following>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Followin__3214EC07F7E6389C");

            entity.ToTable("Following");

            entity.HasOne(d => d.FollowingNavigation).WithMany(p => p.FollowingFollowingNavigations)
                .HasForeignKey(d => d.FollowingId)
                .HasConstraintName("FK__Following__Follo__5812160E");

            entity.HasOne(d => d.User).WithMany(p => p.FollowingUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Following__UserI__59063A47");
        });

        modelBuilder.Entity<Progress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Progress__3214EC0788BB66A6");

            entity.ToTable("Progress");

            entity.HasOne(d => d.BoughtSubject).WithMany(p => p.Progresses)
                .HasForeignKey(d => d.BoughtSubjectId)
                .HasConstraintName("FK__Progress__Bought__4BAC3F29");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3214EC07ABE614F6");

            entity.ToTable("Question");

            entity.Property(e => e.Answers).HasMaxLength(255);
            entity.Property(e => e.CorrectAnswer).HasMaxLength(255);
            entity.Property(e => e.Explaination).HasMaxLength(255);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Question1)
                .HasMaxLength(255)
                .HasColumnName("Question");
            entity.Property(e => e.Type).HasMaxLength(255);

            entity.HasOne(d => d.Topic).WithMany(p => p.Questions)
                .HasForeignKey(d => d.TopicId)
                .HasConstraintName("FK__Question__TopicI__3F466844");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Subject__3214EC078D1EED7E");

            entity.ToTable("Subject");

            entity.Property(e => e.Name).HasMaxLength(255);
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Topic__3214EC072EC309E3");

            entity.ToTable("Topic");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.HasOne(d => d.Chapter).WithMany(p => p.Topics)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("FK__Topic__ChapterId__3C69FB99");
        });

        modelBuilder.Entity<TopicProgress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TopicPro__3214EC073D65CB7D");

            entity.ToTable("TopicProgress");

            entity.HasOne(d => d.Topic).WithMany(p => p.TopicProgresses)
                .HasForeignKey(d => d.TopicId)
                .HasConstraintName("FK__TopicProg__Topic__4F7CD00D");

            entity.HasOne(d => d.User).WithMany(p => p.TopicProgresses)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__TopicProg__UserI__4E88ABD4");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC07E64390ED");

            entity.ToTable("User");

            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.Role).HasMaxLength(255);
            entity.Property(e => e.Username).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}