// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class BoughtSubject
{
    public int Id { get; set; }

    public DateOnly PurchaseDate { get; set; } = DateOnly.FromDateTime(DateTime.Now);

    public string Feedback { get; set; }

    public int SubjectId { get; set; }

    public int UserId { get; set; }
    public int Rating { get; set; }

    public virtual Progress Progress { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual User User { get; set; }
}