// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class Comment
{
    public int Id { get; set; }

    public string Content { get; set; }

    public int? Answer { get; set; }

    public DateOnly? CommentDate { get; set; }

    public int? QuestionId { get; set; }

    public int? UserId { get; set; }

    public virtual Question Question { get; set; }

    public virtual User User { get; set; }
}