// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class Following
{
    public int Id { get; set; }

    public DateOnly? FollowDate { get; set; }

    public int FollowingId { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }
}