// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class Progress
{
    public int Id { get; set; }

    public int Chapter { get; set; }

    public int Topic { get; set; }

    public int BoughtSubjectId { get; set; }

    public virtual BoughtSubject BoughtSubject { get; set; }
}