// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class Subject
{
    public int Id { get; set; }

    public string Name { get; set; }
    public string Image { get; set; }

    public int Price { get; set; }

    public DateOnly? UploadDate { get; set; }

    public DateOnly? LastEditDate { get; set; }

    public virtual ICollection<BoughtSubject> BoughtSubjects { get; set; } = new List<BoughtSubject>();

    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();
}