// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class TopicProgress
{
    public int Id { get; set; }

    public int Score { get; set; }

    public DateOnly? StartDate { get; set; }

    public int UserId { get; set; }

    public int TopicId { get; set; }
    public string Note { get; set; }

    public virtual Topic Topic { get; set; }

    public virtual User User { get; set; }
}