// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudyPlatform.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public int? CuratorId { get; set; }

    public string Email { get; set; }

    public int Point { get; set; }

    public DateOnly? JoinedDate { get; set; }

    public int DayStreak { get; set; }

    public int HighestDayStreak { get; set; }

    public string Image { get; set; }
    public DateOnly? LastOnline { get; set; }
    public string Type { get; set; }

    public virtual ICollection<AccomplishAchievement> AccomplishAchievements { get; set; } = new List<AccomplishAchievement>();

    public virtual ICollection<BoughtSubject> BoughtSubjects { get; set; } = new List<BoughtSubject>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Following> FollowingUsers { get; set; } = new List<Following>();

    public virtual ICollection<TopicProgress> TopicProgresses { get; set; } = new List<TopicProgress>();
    public virtual ICollection<ChapterProgress> ChapterProgresses { get; set; } = new List<ChapterProgress>();
}